name: Verify
on:
  push:
    branches: [v23, v14, v14-gh-actions]
  workflow_dispatch:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set TB License
        run: |
          TBL=${{ secrets.TB_LICENSE }}
          [ -z "$TBL" ] && echo "No TB license provided" && exit 1
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TBL | cut -d / -f1`'","proKey":"'`echo $TBL | cut -d / -f2`'"}' > ~/.vaadin/proKey          
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: nanasess/setup-chromedriver@master          
      - name: Verify
        run: |
          mvn -B -V -ntp verify -Dheadless -Pit,production
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "**/target/*-reports/TEST*.xml"
          check_run_annotations: all tests, skipped tests
